# Generated by Django 2.1 on 2019-02-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190207_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
