# Generated by Django 2.1 on 2019-03-16 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_mainlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='how_to_eat',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='how_to_save',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='utility',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
