# Generated by Django 2.1 on 2019-08-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190724_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='how_to_eat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='how_to_save',
        ),
        migrations.RemoveField(
            model_name='product',
            name='utility',
        ),
    ]
