# Generated by Django 2.1 on 2019-02-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190131_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('Caмовивоз', 'Caмовивоз'), ('Доставка', 'Доставка')], default='Самовывоз', max_length=40),
        ),
    ]
