# Generated by Django 2.1 on 2019-07-22 23:49

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190317_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to=main.models.image_folder)),
            ],
        ),
    ]
