# Generated by Django 2.1 on 2019-07-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sticers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datep',
            field=models.CharField(default='Ближайший', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default='Повна', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='sticker',
            field=models.CharField(default='Звичайний', max_length=40),
        ),
    ]
